[package]
name = "ink_storage_traits"
version = "4.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_storage_traits"
homepage = "https://www.parity.io/"
description = "[ink!] defines traits for using ink storage."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_metadata = { version = "4.0.1", path = "../../metadata", default-features = false, features = ["derive"], optional = true }
ink_primitives = { version = "4.0.1", path = "../../primitives", default-features = false }
ink_prelude = { version = "4.0.1", path = "../../prelude", default-features = false }
scale = { package = "parity-scale-codec", version = "3.4", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
paste = "1.0"

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_primitives/std",
    "ink_prelude/std",
    "scale/std",
    "scale-info/std",
]
